# Generated by Django 2.0.1 on 2018-09-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='auhtor',
            new_name='author',
        ),
    ]
